Objectives:
  - "The goal of this module is to serve as a general utility for interfacting with a WordPress client over XML-RPC."
  - "Instance methods resemble WordPress functions used in PHP development, although conform to camel case naming conventions."

Features:
  - "Connect to WordPress site over XML-RPC and pull available methods using listMethods()."
  - "Automatically batch XML-RPC calls and attempt to process in batches using multiCall()"
  - "Authenticated vs non-authenticated calls are automatically selected based on type of RPC action."
  - "Request and response objects are automatically converted between JSON and XML-RPC structures."
  - "Environment variables WORDPRESS_URL, WORDPRESS_USERNAME and WORDPRESS_PASSWORD are used as defaults for new instances."

Methods:
  - "module.create()"
  - "module.validateLogin()"
  - "module.prototype.validateLogin()"
  - "module.prototype.getPost()"
  - "module.prototype.getPosts()"
  - "module.prototype.getPostTypes()"
  - "module.prototype.getOption()"
  - "module.prototype.insertPost()"
  - "module.prototype.uploadFile()"
  - "module.prototype.multiCall()"
  - "module.prototype.listMethods()"
  - "module.prototype.getMediaItem()"
